spring:
  application:
    name: spring-batch-dynamic-csv-reader

  batch:
    job:
      enabled: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test
    username: admin
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: validate

  h2:
    console:
      path: h2-console

  flyway:
    baseline-on-migrate: true